### ISSUE TITLE
Improvements in API and new TASK to be done

### ISSUE THREAD

**Issue by Tsandesh** [debuggers-pu/hr-connect#17]
1. Reset Password should have old password and new password unique api
2. User Details should have more fields like phone number location and the field username does not have any meaning
3. Update User(SUDO) don't have update feature like user type,(for super user) also do not include password here update validations like minimum and maximum characters 
5. Create an Attendance API fast.
6. Create a Event Schema and API
7. Create a Schema CV applicants where we will keep the cv of people  with id name phone and role s/he is applying to
8. Add validations and everywhere like checking JWT token ,comparing and expiration

**Comment by AtulPatidar1709** [comment]
Hello @Tsandesh, I want to contribute in this can you please assign me.

**Comment by Tsandesh** [comment]
Hello Atul thank you for showing your interest in this project but since
this is our collage project and we have to show all the github commits pull
requests and collaborators we are unable to give you write access.
But please feel free to give it a star, clone and fork the project as you
wish
